version: '3'
services:
    domserver:
        build: ./domserver
        ports:
            - "8080:80"
        env_file:
            - domserver.env
    db:
        image: mariadb
        volumes:
            - ./db:/etc/mysql/conf.d
            - /var/lib/containers/domjudge_db:/var/lib/mysql
        env_file:
            - domserver.env
