version: "3"

services:
  cds:
    image: ghcr.io/icpctools/cds:2.6.1166
    ports:
      - "8084:8080"
      - "8443:8443"
    volumes:
      - ${PWD}/data/contest_main:/contest_main
      - ${PWD}/data/contest_spec:/contest_spec
      - ${PWD}/data/contest_test:/contest_test
      - ${PWD}/data/config:/opt/wlp/usr/servers/cds/config
