version: "3"

services:
  domserver:
    image: ghcr.io/wisvch/domjudge-packaging/domserver:8.3
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    env_file:
        - domserver.env
    links:
      - "mariadb:mariadb"

  mariadb:
    image: mariadb:latest
    ports:
      - "13306:3306"
    env_file:
        - domserver.env
    command: --max-connections=1000
    volumes:
      - ${PWD}/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8081:80"
    depends_on:
      - mariadb
    env_file:
        - domserver.env
    links:
      - "mariadb:db"
