version: "3"

services:
  domserver-spectator:
    image: ghcr.io/wisvch/domjudge-packaging/domserver:8.2.0
    ports:
      - "8082:80"
    depends_on:
      - mariadb-spectator
    env_file:
        - domserver-spectator.env
    links:
      - "mariadb-spectator:mariadb"
    deploy:
        resources:
            limits:
                cpus: '2'
                memory: 4G

  mariadb-spectator:
    image: mariadb:latest
    ports:
      - "13307:3306"
    env_file:
        - domserver-spectator.env
    command: --max-connections=1000

  phpmyadmin-spectator:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8083:80"
    depends_on:
      - mariadb-spectator
    env_file:
        - domserver-spectator.env
    links:
      - "mariadb-spectator:db"
